version: '2'

services:
  base:
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: datacrawlingkraken
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_ROOT_HOST: mywildfly
